### ISSUE TITLE
Run tzcronjob now

### ISSUE THREAD

**Issue by hugochinchilla** [hiddeco/cronjobber#21]
With regular cronjobs you can create jobs from a cronjob when you want to run a task inmediatly:

`kubectl create job --from=cronjob/<name of cronjob> <name of job>`

With cronjobber this does not work:

```
$ kubectl create job --from=tzcronjob/update-campaign-metrics update-campaign-metrics-now
error: from must be an existing cronjob: no kind "TZCronJob" is registered for version "cronjobber.hidde.co/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```
```
$ kubectl create job --from=cronjob/update-campaign-metrics update-campaign-metrics-now
Error from server (NotFound): cronjobs.batch "update-campaign-metrics" not found
```

Would it be possible to fix this?

**Comment by hiddeco** [comment]
See #19

**Comment by hugochinchilla** [comment]
thanks!

**Comment by arobert-delfingen** [comment]
I saw that "kubectl create job --from=tzcronjob/xxxx" will not be implemented, but is there a workaround to manually and immediatly trigger a Timezone Cron Job ?

**Comment by arobert-delfingen** [comment]
The workaround I found is to duplicate the TZCronJob I need to trigger manually in a standard CronJob at status **suspended** . So the TZCronJob is automatically triggered by kubernetes at the right Timezone,  and manually I can run the always suspended standard cronjob through the command `kubectl create job --from=cronjob/xxxx`
