### ISSUE TITLE
 cronjobber-updatetz image - Does not exists

### ISSUE THREAD

**Issue by voslartomas** [hiddeco/cronjobber#26]
Trying to deploy `cronjobber-updatetz` gives error about non existing image, it seems url is not working anymore.

https://quay.io/repository/hiddeco/cronjobber-updatetz

```
  Warning  Failed     8m48s (x4 over 10m)  kubelet, ip-172-20-54-167.ec2.internal  Failed to pull image "quay.io/hiddeco/cronjobber-updatetz:0.1.1": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/: EOF
```

**Comment by hiddeco** [comment]
Quay.io is currently experiencing issues. See: https://status.quay.io

**Comment by voslartomas** [comment]
@hiddeco It seems there is still something wrong, qay is okay already, but image is not found. I cannot see 0.1.1 here https://quay.io/repository/hiddeco/cronjobber-updatetz?tag=0.1.1&tab=tags

**Comment by hiddeco** [comment]
Sorry about that, should be available now.

**Comment by voslartomas** [comment]
Great, works now, thanks!
