### ISSUE TITLE
[Q&A] Programmatically create a TZCronJob

### ISSUE THREAD

**Issue by afabriciof** [hiddeco/cronjobber#27]
Great Job! Thanks for sharing!.

I have a (probably) dummy question. How can I programmatically create a TZCronJob (in particular, I am using python). Is there and endpoint I need to call?

As reference, for regular CronJob, I am using pip package kubernetes==9.0.0 doing this:

cron_job.spec = V1beta1CronJobSpec(job_template=job_template, schedule=schedule)

client.BatchV1beta1Api(self._client).create_namespaced_cron_job(namespace_name, body=cron_job)

which in turn ends up calling

 '/apis/batch/v1beta1/namespaces/{namespace}/cronjobs', 'POST'

Any advise very welcomed!
Alex

**Comment by Nick-Triller** [comment]
Hi @afabriciof, the issue is kind of old, but just in case: you can find an example of how to create custom resources with the Python Kubernetes client here: https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py

I think this issue can be closed.

**Comment by afabriciof** [comment]
Thank you Nick, yes please go ahead and close the ticket.
